import styles from "./homepage.module.css"
import Head from "next/head"

type HomePageProps = {
  title: string
  slots: {
    header: React.ReactNode
    main: React.ReactNode
    sidebar: React.ReactNode
    footer: React.ReactNode
  }
}

const HomePage = ({
  title,
  slots: { header, main, sidebar, footer },
}: HomePageProps) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <header className={styles.header}>{header}</header>
        <main className={styles.main}>{main}</main>
        <aside className={styles.sidebar}>{sidebar}</aside>
        <footer className={styles.footer}>{footer}</footer>
      </div>
    </>
  )
}
export default HomePage
